version: "3"
services:
  node: &defaults
    image: tomasbasham/node:6.11.0
    volumes:
      - .:/usr/src/app

  npm:
    <<: *defaults
    entrypoint: ["/usr/local/bin/npm"]

  bower:
    <<: *defaults
    entrypoint: ["/usr/local/bin/bower", "--allow-root"]

  travis:
    image: tomasbasham/travis:1.8.8
    volumes:
      - travis-data:/root/.travis
      - .:/usr/src/app

volumes:
  travis-data:
    external: true
